version: "3.9"
services:

  vyf-usersvc-cache:
    image: redis:6.2
    volumes:
      - ./cache/redis-data:/var/lib/redis
    networks:
      - n_usersvc
    env_file:
      - .env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_TIMEOUT=${REDIS_TIMEOUT}
      - REDIS_PWD=${REDIS_PASSWORD}
      - REDIS_REPLICATION_MODE=master
    command: >
      redis-server --requirepass ${REDIS_PASSWORD?Variable not set}

  vyf-usersvc:
    container_name: ${DOCKER_SERVICE_NAME?Variable not set}
    hostname: ${DOCKER_SERVICE_NAME?Variable not set}
    networks:
      - n_usersvc
      - postgres-db-1-public
    image: '${DOCKER_IMAGE_SERVICE_NAME?Variable not set}:${TAG-latest}'
    depends_on:
      - vyf-usersvc-cache
    env_file:
      - .env
    build:
      context: .
      dockerfile: service.dockerfile

networks:
  n_usersvc:
  postgres-db-1-public:
    external: true