# web service
port: 8080

# hosts
host:
  service:
    voteCircle: http://127.0.0.1:8080/v1/api/vote-circle

# aws
aws:
  auth:
    clientId: clientId
    userPoolId: poolId
    awsDefaultRegion: eu-central-1
    clientSecret: secret
  s3:
    accessKeyId: keyId
    accessKeySecret: secret
    region: eu-central-1
    bucketName: bucket
    uploadTimeout: 100
    defaultBaseURL: url

# Database
db:
  host: publicPostgresDb
  port: 5432
  name: name
  user: user
  password: pwd
  test:
    host: db
    port: 5432
    name: tname
    user: user
    password: pwd

# Security
security:
  secrets:
    key: secret

# TTL's
# given in seconds
ttl:
  default: 300 # 5 min.
  token:
    default: 300 # 5 min.
    account:
      activation: 5400 # 90 min.
      verification: 604800 # 1 week
      password: 5400 # 90 min.

# used token definitions
token:
  type: bearer

user:
  admin:
    email: admin@vecomentman.de
    name: admin
    password: pwd
